version: 2.0
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run:
          name: "Install node, zip and ghr"
          command: |
            cd ~
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
            source /root/.bashrc
            nvm install node
            apt update
            apt -y install zip
            wget https://github.com/tcnksm/ghr/releases/download/v0.12.1/ghr_v0.12.1_linux_amd64.tar.gz
            tar -C /usr/local/bin -xf ghr_v0.12.1_linux_amd64.tar.gz --strip-components=1 ghr_v0.12.1_linux_amd64/ghr
            mkdir artifacts

      - run:
          name: "Publish project at target windows"
          command: |
            source /root/.bashrc
            dotnet publish -c Release -r win10-x64

      - run:
          name: "Package Main Project"
          command: |
            cd Infobase/bin/Release/netcoreapp3.0/win10-x64/publish
            zip -qr ~/artifacts/Web-$CIRCLE_PROJECT_REPONAME-$CIRCLE_PROJECT_USERNAME-$CIRCLE_BRANCH-win10-x64.zip .

      - run:
          name: "Package Model Generator Project"
          command: |
            cd Model-Generator/bin/Release/netcoreapp3.0/win10-x64/publish
            zip -qr ~/artifacts/Model-Generator-$CIRCLE_PROJECT_REPONAME-$CIRCLE_PROJECT_USERNAME-$CIRCLE_BRANCH-win10-x64.zip .

      - run:
          name: "Upload to GitHub"
          command: |
            ghr -n 'Latest build by CircleCI' -b "Build $CIRCLE_BUILD_NUM for project **$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BRANCH** completed at **$(date)**. [View here]($CIRCLE_BUILD_URL)" --delete latest ~/artifacts
      
      - store_artifacts:
          path: ~/artifacts
