version: 2.0
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
      - image: node
    steps:
      - checkout
      - run:
          name: "Publish project with windows"
          command: |
            dotnet publish -r win10-x64